---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
  - vault.yml
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Destroy molecule instance(s)
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ molecule_yml.driver.validate_certs | default(false) }}"
        datacenter: "{{ molecule_yml.driver.datacenter }}"
        cluster: "{{ molecule_yml.driver.cluster | default(omit) }}"
        esxi_hostname: "{{ molecule_yml.driver.esxi_hostname | default(omit) }}"
        folder: "{{ molecule_yml.driver.folder }}"
        name: "{{ item.name }}"
        force: true
        state: absent
      no_log: false
      async: 7200
      poll: 0
      register: async_results
      with_items: "{{ molecule_yml.platforms }}"

    - name: Check the test instance destroying status
      async_status:
        jid: "{{ item.ansible_job_id }}"
      loop: "{{ async_results.results }}"
      register: server
      until: server.finished
      delay: 10
      retries: 300
