common_services:
  - AppHostSvc
  - venAgentMgrSvc
  - venAgentMonitorSvc
  - venPlatformHandlerSvc
  - venVtapServerSvc
  - Appinfo
  - BFE
  - BITS
  - AmazonSSMAgent
  - AppReadiness
  - Netman
  - lfsvc
  - MpsSvc
  - MsDtsServer130
  - MSiSCSI
  - Netman
  - sacsvr
  - WdiSystemHost
  - RemoteRegistry
  - sppsvc
  - TrustedInstaller
  - VSS
  - SNMP
  - swprv
  - wmiApSrv
  - BrokerInfrastructure
  - camsvc
  - cbdhsvc_78d15857
  - CertPropSvc
  - COMSysApp
  - CoreMessagingRegistrar
  - CryptSvc
  - CSFalconService
  - db-fluent-bit
  - db-windows-exporter
  - DcomLaunch
  - Dhcp
  - DispBrokerDesktopSvc
  - Dnscache
  - DPS
  - DsSvc
  - EFS
  - EventLog
  - EventSystem
  - FontCache
  - gpsvc
  - IISADMIN
  - IKEEXT
  - iphlpsvc
  - KeyIso
  - LanmanServer
  - LanmanWorkstation
  - lmhosts
  - LSM
  - mpssvc
  - MSDTC
  - MSSQL$MICROSOFT##WID
  - Netlogon
  - netprofm
  - NetSetupSvc
  - nightwatch
  - NlaSvc
  - nsi
  - PlugPlay
  - PolicyAgent
  - Power
  - ProfSvc
  - QualysAgent
  - RpcEptMapper
  - RpcSs
  - SamSs
  - Schedule
  - SENS
  - sensu-client
  - SessionEnv
  - ShellHWDetection
  - smphost
  - Spooler
  - StateRepository
  - StorSvc
  - SystemEventsBroker
  - TermService
  - Themes
  - TimeBrokerSvc
  - TokenBroker
  - TrkWks
  - UALSVC
  - UmRdpService
  - UserManager
  - UsoSvc
  - vds
  - VGAuthService
  - VM3DService
  - VMTools
  - W32Time
  - W3SVC
  - WAS
  - WdiServiceHost
  - WerSvc
  - WIDWriter
  - WinHttpAutoProxySvc
  - Winmgmt
  - WinRM
  - WpnService
  - WpnUserService_78d15857
  - WsusService
  - WaaSMedicSvc
  - wuauserv
